spring.application.name=demo

server.port=8080

# MongoDB Connection
spring.data.mongodb.host=localhost
spring.data.mongodb.port=27017
spring.data.mongodb.database=TestDB

# Actuator - expose health endpoint
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always